[theme]
base="dark"
primaryColor="#3399FF"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"

[server]
maxUploadSize = 200
enableCORS = false
headless = true

[ui]
hideTopBar = false

[client]
showSidebarNavigation = true


